"""Pick + apply a theme recipe (palette, font pair, radius, per-section layout variants).

Writes the theme's tokens.css from the recipe and - with --mods - sets the WordPress
theme mods that front-page.php / functions.php read. The recipe is chosen
deterministically from the domain (so re-runs are stable) unless
config/<domain>.brief.json already pins one under design.recipe. Catalog:
config/theme-recipes.json.

Run:
  python -m scripts.apply_theme <domain>          # pick recipe + write tokens.css (+ record in brief)
  python -m scripts.apply_theme <domain> --mods   # also set theme mods on the live WP (theme must be active)
"""
from __future__ import annotations

import hashlib
import json
import random
import sys
from pathlib import Path

from scripts.config import AGENT_DIR, load_config
from scripts.wp import WPClient

THEME_SLUG = "overlaytop"
RECIPES_PATH = AGENT_DIR / "config" / "theme-recipes.json"
TOKENS_PATH = AGENT_DIR / "assets" / "master-theme" / THEME_SLUG / "assets" / "css" / "tokens.css"
DEFAULT_FONTS = (
    "https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,500;9..144,600;9..144,700"
    "&family=Inter:wght@400;500;600;700&display=swap"
)


def _load_recipes() -> dict:
    return json.loads(RECIPES_PATH.read_text(encoding="utf-8"))


def _brief_path(domain: str) -> Path:
    return AGENT_DIR / "config" / f"{domain}.brief.json"


def _seeded_rng(domain: str) -> random.Random:
    return random.Random(int(hashlib.md5(domain.encode("utf-8")).hexdigest(), 16))


def _find(items: list, name: str) -> dict:
    for item in items:
        if item.get("name") == name:
            return item
    return items[0]


def pick_recipe(domain: str, brief: dict, cat: dict) -> dict:
    """Return the recipe to use - honoring a brief-pinned one, else a seeded pick."""
    existing = (brief.get("design") or {}).get("recipe") or {}
    if existing.get("palette"):
        return existing
    rng = _seeded_rng(domain)
    niche = (brief.get("niche") or domain or "").lower()
    words = {w for w in niche.replace("&", " ").replace("-", " ").split() if len(w) > 2}
    matches = [p for p in cat["palettes"] if set(p.get("niches", [])) & words]
    palette = rng.choice(matches) if matches else rng.choice(cat["palettes"])
    v = cat["variants"]
    return {
        "palette": palette["name"],
        "font": rng.choice(cat["fonts"])["name"],
        "radius": rng.choice(list(cat["radii"].keys())),
        "density": rng.choice(list(cat["density"].keys())),
        "hero": rng.choice(v["hero"]),
        "about": rng.choice(v["about"]),
        "latest": rng.choice(v["latest"]),
        "category": rng.choice(v["category"]),
        "newsletter": rng.choice(v["newsletter"]),
        "footer": rng.choice(v["footer"]),
    }


def write_tokens_css(recipe: dict, cat: dict) -> str:
    pal = _find(cat["palettes"], recipe["palette"])
    font = _find(cat["fonts"], recipe["font"])
    rad = cat["radii"][recipe["radius"]]
    dens = cat["density"][recipe["density"]]
    return f"""/* Overlaytop design tokens - recipe "{recipe['palette']} / {recipe['font']} / {recipe['radius']}".
   Generated by scripts.apply_theme from config/theme-recipes.json. Do not hand-edit - re-run apply_theme.
   Fonts are loaded via the ot_fonts_href theme mod (set with --mods); structural tokens stay constant. */
:root{{
  --bg:{pal['bg']}; --surface:{pal['surface']}; --soft:{pal['soft']};
  --text:{pal['text']}; --text-muted:{pal['muted']};
  --primary:{pal['primary']}; --primary-strong:{pal['primary_ink']}; --on-primary:#ffffff;
  --accent:{pal['accent']}; --line:{pal['line']}; --dark:{pal['dark']};

  --font-serif:{font['head_stack']};
  --font-sans:"{font['body']}", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;

  --max-w:1180px; --read-w:740px;
  --gutter:clamp(1rem, 2.6vw, 1.75rem);
  --section-y:{dens['section']}; --grid-gap:{dens['gap']};
  --radius-sm:{rad['sm']}; --radius:{rad['md']}; --radius-lg:{rad['lg']}; --radius-xl:{rad['lg']};
  --shadow-sm:0 1px 2px rgba(20,24,28,.04);
  --shadow:0 6px 22px rgba(20,24,28,.06);
  --shadow-lg:0 18px 44px rgba(20,24,28,.08);
  --t-fast:140ms cubic-bezier(.4,0,.2,1); --t:240ms cubic-bezier(.4,0,.2,1);
  --header-h:74px;

  /* Back-compat aliases: the legacy brand-ramp names main.css still references,
     mapped onto the semantic palette so any recipe keeps the existing site working. */
  --cream:var(--bg); --paper:var(--surface);
  --ink-900:var(--text); --ink-700:var(--text); --ink-500:var(--text-muted); --ink-300:var(--text-muted);
  --teal-50:var(--soft); --teal-100:var(--soft); --teal-300:var(--soft);
  --teal-500:var(--primary); --teal-700:var(--primary-strong); --teal-900:var(--dark);
  --accent-dark:var(--primary-strong); --line-soft:var(--soft);
}}
"""


def set_mods(client: WPClient, recipe: dict, font: dict) -> None:
    mods = {
        "ot_recipe": recipe["palette"],
        "ot_v_hero": recipe["hero"],
        "ot_v_about": recipe["about"],
        "ot_v_latest": recipe["latest"],
        "ot_v_category": recipe["category"],
        "ot_v_newsletter": recipe["newsletter"],
        "ot_v_footer": recipe["footer"],
        "ot_fonts_href": f"https://fonts.googleapis.com/css2?{font['google']}&display=swap",
    }
    for key, val in mods.items():
        client.wp(["theme", "mod", "set", key, val])


def main() -> int:
    raw = sys.argv[1:]
    do_mods = "--mods" in raw
    pos = [a for a in raw if not a.startswith("--")]
    if not pos:
        print("usage: python -m scripts.apply_theme <domain> [--mods]")
        return 2
    domain = pos[0]
    cat = _load_recipes()
    bp = _brief_path(domain)
    brief = json.loads(bp.read_text(encoding="utf-8")) if bp.exists() else {"niche": domain}

    recipe = pick_recipe(domain, brief, cat)
    font = _find(cat["fonts"], recipe["font"])

    if bp.exists():
        brief.setdefault("design", {})["recipe"] = recipe
        bp.write_text(json.dumps(brief, indent=2, ensure_ascii=False), encoding="utf-8")

    TOKENS_PATH.write_text(write_tokens_css(recipe, cat), encoding="utf-8")
    print(
        f"recipe: {recipe['palette']} / {recipe['font']} / radius={recipe['radius']} / density={recipe['density']}\n"
        f"  layout: hero={recipe['hero']} about={recipe['about']} latest={recipe['latest']} "
        f"category={recipe['category']} newsletter={recipe['newsletter']} footer={recipe['footer']}"
    )
    print(f"wrote tokens.css -> {TOKENS_PATH}")

    if do_mods:
        client = WPClient(load_config())
        client.verify()
        set_mods(client, recipe, font)
        client.close()
        print("set theme mods on live WordPress.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
